esphome:
  name: fp2-sala

esp32:
  board: esp32-solo1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: "y"
      CONFIG_ESP_SYSTEM_SINGLE_CORE_MODE: "y"
    advanced:
      ignore_efuse_mac_crc: true
      ignore_efuse_custom_mac: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "FP2 Fallback"
    password: !secret ap_password

captive_portal:

api:
  encryption:
    key: !secret api_encryption_key

  actions:
    - action: get_map_config
      supports_response: only
      then:
        - api.respond:
            data: !lambda |-
              id(fp2).json_get_map_data(root);
    - action: fp2_force_detection_config
      then:
        - lambda: |-
            id(fp2).force_detection_config();
    - action: fp2_configure_sleep_mode
      variables:
        width: int
        length: int
        mount_position: int
      then:
        - lambda: |-
            id(fp2).configure_sleep_mode((uint16_t) width, (uint16_t) length, (uint8_t) mount_position);
    - action: fp2_set_work_mode
      variables:
        mode: int
      then:
        - lambda: |-
            id(fp2).set_work_mode((uint8_t) mode);
    - action: fp2_calibrate_empty_room
      then:
        - lambda: |-
            id(fp2).calibrate_empty_room();
    - action: fp2_reset_radar
      then:
        - lambda: |-
            id(fp2).reset_radar();

ota:
  - platform: esphome
    password: !secret ota_password

logger:
  level: INFO

uart:
  id: uart_bus
  tx_pin: GPIO19
  rx_pin: GPIO18
  baud_rate: 890000

i2c:
  sda: GPIO33
  scl: GPIO32
  scan: true
  frequency: 100kHz

external_components:
  - source:
      type: git
      url: https://github.com/tigercraft4/esphome_fp2
      ref: main
    components: [aqara_fp2, aqara_fp2_accel]

aqara_fp2_accel:
  id: fp2_accel

aqara_fp2:
  id: fp2
  accel: fp2_accel
  uart_id: uart_bus
  radar_reset_pin: GPIO13
  mounting_position: left_corner
  left_right_reverse: false

  people_counting_report_enable: true
  people_number_enable: true
  target_type_enable: false
  dwell_time_enable: false
  walking_distance_enable: false
  thermodynamic_chart_enable: true

  target_tracking:
    name: "Targets"

  location_report_switch:
    name: "Report Targets"

  interference_grid: |-
    . . . . . . . . . . . . . .
    . . . . . . . . . . . . . .
    . . . . . . . . . . . . . .
    . . . . . . . . . . . . . .
    . . . . . . . . . . . . . .
    . . . . . . . . . . . . . .
    . . . . . . . . . . . . . .
    . . . . . . . . . . . . . .
    . . . . . . . . . . . . . .
    . . . . . . . . . . . . . .
    . . . . . . . . . . . . . .
    . . . . . . . . . . . . . .
    . . . . . . . . . . . . . .
    . . . . . . . . . . . . . .

  global_zone:
    presence_sensitivity: medium
    presence:
      name: "Global Presence"
    motion:
      name: "Global Motion"

  radar_software_version:
    name: "Radar Software Version"
  radar_temperature:
    name: "Radar Temperature"
  radar_debug:
    name: "Radar Debug"
  realtime_people_number:
    name: "Realtime People Number"
  ontime_people_number:
    name: "Ontime People Number"
  realtime_people_counting:
    name: "Realtime People Counting"
  people_counting:
    name: "People Counting"
  walking_distance:
    name: "Walking Distance"
  sleep_data:
    name: "Sleep Data"
  sleep_presence:
    name: "Sleep Presence"
  sleep_inout_state:
    name: "Sleep In Out State"
  sleep_state:
    name: "Sleep State"
  sleep_event:
    name: "Sleep Event"
  target_posture:
    name: "Target Posture"

sensor:
  - platform: opt3001
    name: "Illuminance"
    address: 0x44
    update_interval: 30s

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO36
      inverted: true
    name: "Device Button"

output:
  - platform: ledc
    id: status_led_red
    pin: GPIO14
    inverted: true
  - platform: ledc
    id: status_led_green
    pin: GPIO26
    inverted: true
  - platform: ledc
    id: status_led_blue
    pin: GPIO27
    inverted: true

light:
  - platform: rgb
    name: "Status LED"
    red: status_led_red
    green: status_led_green
    blue: status_led_blue

button:
  - platform: template
    name: "FP2 Force Detection Config"
    entity_category: diagnostic
    on_press:
      - lambda: |-
          id(fp2).force_detection_config();
  - platform: template
    name: "FP2 Calibrate Empty Room"
    entity_category: diagnostic
    on_press:
      - lambda: |-
          id(fp2).calibrate_empty_room();
  - platform: template
    name: "FP2 Reset Radar"
    entity_category: diagnostic
    on_press:
      - lambda: |-
          id(fp2).reset_radar();
